name: "brook"
port: "6002"
log: "/Users/dxavier/Library/Logs/BrookHttp"
gatekeeper: "/Users/dxavier/Developer/brook-http/config/gatekeeper.json"

beanstalkd:
  host: "127.0.0.1"
  port: "11301"

redis:
  host: "127.0.0.1"
  port: "6380"
